# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
- task: deploy-aas-db@1
  inputs:
    connectedServiceNameSelector: 'ConnectedServiceNameARM'
    connectedServiceNameARM: 'pjpayasugo(f7a522a7-655e-4268-addf-d4e8d2d5fd55)'
    aasServer: 'asazure://westindia.asazure.windows.net/pjanalysisservices:rw'
    adminName: 'User P J'
    adminPassword: 'Term.0.12'
    pathToModel: 'FirstTabularProject/Model.bim'
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
